name: Run Fuzz Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fuzzing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install ruamel.yaml atheris

    - name: Run fuzzing script
      run: |
        python3 KubeSec-master/fuzz.py || true

    - name: Upload fuzz log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: fuzz-logs
        path: fuzz_errors.log
