name: Fuzz Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  fuzz:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run fuzzing tests
      run: |
        python fuzz.py
        
    - name: Archive fuzzing results
      uses: actions/upload-artifact@v3
      with:
        name: fuzzing-results
        path: fuzzing_results/
        retention-days: 14
