name: Python Fuzzing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger

jobs:
  fuzz:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run fuzzing
      run: |
        python fuzz.py
    
    - name: Upload fuzzing results
      uses: actions/upload-artifact@v2
      with:
        name: fuzzing-results
        path: |
          fuzzing_results/
          fuzz_results.log
